### ISSUE TITLE
[Suggestion] Auto cleanup

### ISSUE THREAD

**Issue by boskos-q** [cpjet64/ScavengersUE4SupportTool#7]
Thanks for this tool, tho I'd suggest a slight modification of it, to add option to auto remove files at the end.

E.g. Script finishes running, pop a question `"Do you want to remove downloaded files?" (default No)`
If yes, move log file to the desktop (or just in downloads folder - one level up), delete downloaded scripts and SST folder
Notify user that log is now located on the desktop - c:/<user>/Desktop/SST.log which he/she can then send to the Hayden

**Comment by cpjet64** [comment]
Sorry for the delayed reply! This is actually a wonderful suggestion and I have implemented it in the development branch I have been working on. In the new version, everything is fully automated to include cleanup and discord tasks and it will no longer go to Hayden it will now go to a special locked and hidden channel in the official discord where the devs can sort through them directly instead of us middlemen having to pass it along as Hayden just puts it in that channel already. The dev version has a issue with the exe packager so its not ready for use just yet but the dev of my packaging software is aware of and is already working on fixing it so hopefully sometime this week the dev branch will go live and people will use that from now on. I would love for you to take a look at the dev branches readme and see if you have any suggestions or questions! 
https://github.com/cpjet64/ScavengersUE4SupportTool/tree/DEV
